"""
-- Constants prject --
"""
from pathlib import Path

base_json_file = Path('.data' ,'channels_last_video.json')

BASE_DOWNLOAD_PATH = 'downloads'
BASE_URL_FILE = Path('test.txt')
BASE_JSON_FILE = '.data/channels_last_video.json'
BASE_TXT_LIST_PATH = Path('urls')
BASE_CSV_LIST_PATH = Path('csv')

BASE_VIDEO_BLOCK_TITLES =  [
    "video's",
    'ቪዲዮዎች', 
    'الفيديو', 
    'video', 
    'видео', 
    'відэа', 
    'видео', 
    'ভিডিও', 
    'video', 
    'vídeos', 
    'video', 
    'videa', 
    'fideos', 
    'videoer', 
    'videos', 
    'βίντεο',
    'videos', 
    'videoj', 
    'videos', 
    'videod', 
    'bideoak', 
    'ویدئوها', 
    'videot', 
    'vidéos', 
    'físeáin', 
    'bhidiothan', 
    'vídeos', 
    'વિડિઓઝ', 
    'קטעי', 
    'וידאו', 
    'वीडियो', 
    'video', 
    'videyo', 
    'videók', 
    'լուսանկար', 
    'video', 
    'myndbönd', 
    'video', 
    'ビデオ', 
    'video', 
    'ვიდეოები', 
    'видео', 
    'វីដេអូ', 
    'ವೀಡಿಯೊಗಳು', 
    '동영상', 
    'видео', 
    'videos', 
    'videoen', 
    'ວິດີໂອ', 
    'vaizdo', 
    'įrašai', 
    'video', 
    'lahatsary', 
    'видео', 
    'ataata', 
    'видеа', 
    'videos', 
    'видео', 
    'व्हिडिओ', 
    'видео', 
    'video', 
    'vidjows', 
    'ဗီဒီယိုများ', 
    'भिडियो', 
    'video\'s',
    'videoer', 
    'ਵੀਡੀਓ', 
    'video', 
    'video', 
    'videos', 
    'videoclipuri', 
    'වීඩියෝ', 
    'videá', 
    'video', 
    'posnetki', 
    'video', 
    'видео', 
    'video', 
    'videoklipp', 
    'video', 
    'வீடியோக்கள்', 
    'వీడియోలు', 
    'видео', 
    'วีดีโอ', 
    'video', 
    'videolar', 
    'видео', 
    'video', 
    'відео', 
    'ویڈیوز', 
    'videos', 
    'video', 
    'videos', 
    'ווידיאס', 
    '视频'
    ]
